### PR TITLE
Update test suite and add Gemfile for easier contributing

### PR DESCRIPTION
**Pull request by redross**
First off all added development dependencies and a Gemfile, so that setting up the gem for testing would be  as easy as it gets.

Then removed patched MockRedis (it seems it is not needed anymore since "pipelined" isn't used anywhere).

Lastly cleaned up/refactored the specs.

This might be not the cleanest of pull requests so if You see any issues, please let me know.

### CODE REVIEW

**Comment by redross** [comment]
My next plan is to make a separate PR that would check for redis version and use `MIGRATE` command if its supported.

**Comment by yankov** [comment]
Looks great, the only thing: when running test for a known key it prints

```
 when known set key
      should #<RSpec::Mocks::Matchers::Receive:0x007faaaceebcf0>
```

was it supposed to be this way?

**Comment by redross** [comment]
Maybe I'm using some other formatting option, I only see a list of green dots :laughing: 
Is this better?

**Comment by yankov** [comment]
It's good now. Thanks for the contribution!

**Pull request merged**
